# Generated by Django 5.1.4 on 2024-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveIntegerField()),
                ('Charger_Name', models.CharField(max_length=100)),
                ('Price', models.PositiveIntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Electronics_Photo/')),
                ('Waranty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Earphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveIntegerField()),
                ('Earphone_Name', models.CharField(max_length=100)),
                ('Price', models.PositiveIntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Electronics_Photo/')),
                ('Waranty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveSmallIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Generation', models.CharField(max_length=40)),
                ('Brand', models.CharField(max_length=100)),
                ('ModeL', models.CharField(max_length=100)),
                ('Ram', models.PositiveIntegerField()),
                ('Storage', models.PositiveIntegerField()),
                ('Core', models.PositiveIntegerField()),
                ('Image', models.ImageField(upload_to='Electronics_Photo/')),
                ('Design_Capacity', models.PositiveIntegerField()),
                ('Full_Charge_Capacity', models.PositiveIntegerField()),
                ('Screen_Size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveSmallIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Mobile_Name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('ModeL', models.CharField(max_length=100)),
                ('Ram', models.PositiveIntegerField()),
                ('Storage', models.PositiveIntegerField()),
                ('Image', models.ImageField(upload_to='Electronics_Photo/')),
                ('Android', models.PositiveIntegerField()),
                ('Battery', models.PositiveIntegerField()),
                ('Screen_Size', models.PositiveIntegerField()),
                ('Camera_Qyality', models.CharField(max_length=100)),
                ('Network', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
